using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System;

namespace Content.Client._Eventide.RadioBoombox
{
    [GenerateTypedNameReferences]
    public sealed partial class RadioBoomboxWindow : DefaultWindow // Изменено тут
    {
        public event Action? OnPlayPressed;
        public event Action<string>? OnUrlConfirmed;

        public RadioBoomboxWindow()
        {
            RobustXamlLoader.Load(this);

            AddUrlButton.OnPressed += _ => UrlContainer.Visible = !UrlContainer.Visible;
            CancelButton.OnPressed += _ => UrlContainer.Visible = false;

            PlayButton.OnPressed += _ => OnPlayPressed?.Invoke();
            ConfirmButton.OnPressed += _ => 
            {
                OnUrlConfirmed?.Invoke(UrlInput.Text);
                UrlContainer.Visible = false;
            };
        }
    }
}
