using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Eventide.RadioBoombox
{
    [GenerateTypedNameReferences]
    public sealed partial class RadioBoomboxWindow : ControlWindow
    {
        public event Action? OnPlayPressed;
        public event Action<string>? OnUrlConfirmed;

        public RadioBoomboxWindow()
        {
            RobustXamlLoader.Load(this);

            // Логика кнопки "+" (показать/скрыть ввод ссылки)
            AddUrlButton.OnPressed += _ => UrlContainer.Visible = !UrlContainer.Visible;

            // Кнопка отмены скрывает меню ввода
            CancelButton.OnPressed += _ => UrlContainer.Visible = false;

            // Кнопки отправки событий в BUI
            PlayButton.OnPressed += _ => OnPlayPressed?.Invoke();
            ConfirmButton.OnPressed += _ => 
            {
                OnUrlConfirmed?.Invoke(UrlInput.Text);
                UrlContainer.Visible = false;
            };
        }
    }
}
