- type: antagSpecifier
  abstract: true
  id: BaseAntagSpecifier
  jobBlacklist:
  - CentralCommandOfficial
  - DeathSquad
  - ERTLeader
  - ERTChaplain
  - ERTEngineer
  - ERTSecurity
  - ERTMedical
  - ERTJanitor
  - CBURN
  - CentComOfficial
  - CentComConsultant
  - CentComOperator
  - CentralCommandAssistant
  - CentralCommandEngineer
  - CentralCommandMedicalDoctor
  - CentralCommandSecurityOfficer
  - HeadOfSecurityCentCom
  - HeadOfStaffCentCom
  - ERTLeaderGamma
  - ERTEngineerGamma
  - ERTSecurityGamma
  - ERTMedicalGamma
  - ERTJanitorGamma
  - ERTLeaderDelta
  - ERTEngineerDelta
  - ERTSecurityDelta
  - ERTMedicalDelta
  - ERTJanitorDelta
  - ERTLeaderBravo
  - ERTEngineerBravo
  - ERTSecurityBravo
  - ERTMedicalBravo
  - ERTJanitorBravo
  - ERTLeaderCharlie
  - ERTEngineerCharlie
  - ERTSecurityCharlie
  - ERTMedicalCharlie
  - ERTJanitorCharlie
  - BlueShield
  - JediNT
  - Magistrat
  - Prisoner
  - SeniorService
  blacklist:
    components:
    - AntagImmune

# Command
- type: antagSpecifier
  abstract: true
  parent: BaseAntagSpecifier
  id: CommandBlacklistedAntag
  jobBlacklist:
  - Captain
  - HeadOfPersonnel
  - HeadOfSecurity
  - ChiefMedicalOfficer
  - ResearchDirector
  - ChiefEngineer
  - Quartermaster
  - IAA # Corvax-Role
  - Magistrate # Corvax-Role

# Borgs
- type: antagSpecifier
  abstract: true
  parent: BaseAntagSpecifier
  id: CyborgBlacklistedAntag
  jobBlacklist:
  - StationAi
  - Borg

# Learner Roles
- type: antagSpecifier
  abstract: true
  parent: BaseAntagSpecifier
  id: InternBlacklistedAntag
  jobBlacklist:
  - SecurityCadet
  - MedicalIntern
  - ResearchAssistant
  - TechnicalAssistant
  - Visitor

# Security
- type: antagSpecifier
  abstract: true
  parent: BaseAntagSpecifier
  id: SecurityBlacklistedAntag
  jobBlacklist:
  - HeadOfSecurity
  - Warden
  - Detective
  - SecurityOfficer
  - SecurityCadet
  - Brigmedic # Corvax-Role
  - Pilot # Corvax-Role
  - SeniorOfficer # Corvax-Role

- type: antagSpecifier
  abstract: true
  parent: [ CommandBlacklistedAntag, SecurityBlacklistedAntag ]
  id: MindshieldRestrictedAntag

- type: antagSpecifier
  abstract: true
  parent: [ MindshieldRestrictedAntag, CyborgBlacklistedAntag, InternBlacklistedAntag ]
  id: RestrictedAntag
  jobBlacklist:
  - TramDriver
