name: "Labels: Untriaged"

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  add_label:
    if: ${{ (github.event_name == 'issues' && join(github.event.issue.labels) == '') || (github.event_name == 'pull_request' && join(github.event.pull_request.labels) == '') }}
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "S: Untriaged"
