name: "Labels: Review"

on:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

jobs:
  add_label:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "S: Needs Review"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "S: Awaiting Changes"
